version: '3.8'

services:
  antink-server:
    build: .
    container_name: antink-server
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./it24_host:/mnt/source
      - ./antink_mount:/mnt/mount
      - ./antink_logs:/var/log
    command: ["./antink", "/mnt/mount", "-f"]
