version: "3.8"

services:
  antink-fuse:
    build: .
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    volumes:
      - type: bind
        source: ./it24_host
        target: /it24_host           # Store Original File
      - type: bind
        source: ./antink_logs
        target: /antink_logs         # Store Log
      - type: volume
        source: antink_mount_vol
        target: /antink_mount        # Mount Point (FUSE, tidak perlu host lihat)
    tty: true
    stdin_open: true

volumes:
  antink_mount_vol:
